name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: '1.21'
commands:
  ability:
    description: Trigger your power.
  controls:
    description: Toggle swap-hand hotkeys.
  trust:
    description: Trust a player.
  untrust:
    description: Untrust a player.
  give-reroll:
    permission: elementsmp.admin
  give-chaos:
    permission: elementsmp.admin
  elementsmp:
    description: Main admin command. Usage /elementsmp <reload|player> [element]
    permission: elementsmp.admin
permissions:
  elementsmp.admin:
    default: op
