name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: '1.21'
commands:
  ability:
    description: Trigger your power.
  controls:
    description: Toggle hotkeys.
  give-reroll:
    permission: elementsmp.admin
  give-chaos:
    permission: elementsmp.admin
  elementsmp:
    description: Admin element control.
    permission: elementsmp.admin
permissions:
  elementsmp.admin:
    default: op
