name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: '1.20'
commands:
  ability:
    description: Use your power.
  controls:
    description: Toggle swap-hand triggers.
  trust:
    description: Trust a teammate.
  untrust:
    description: Untrust a teammate.
  give-reroll:
    permission: op
  give-chaos:
    permission: op
  elementsmp:
    permission: op
