name: ElementSMP
version: 1.0.8-SOVEREIGN
main: me.kaloni.ElementSMP
api-version: "1.21"
description: Advanced 11-Element system with Archon AI and Domain Expansion.
commands:
  elemental:
    description: Master command for lore and element assignment.
    usage: /elemental [set] [player] [element]
  spawnarchon:
    description: Admin command to spawn the Elemental Boss.
    permission: elementsmp.admin
permissions:
  elementsmp.admin:
    description: Access to administrative elemental commands.
    default: op
