name: ElementSMP
version: 1.0.8-FIXED
main: me.kaloni.ElementSMP
api-version: "1.21"
description: Advanced 11-Element framework with Domain Logic and Archon AI.
commands:
  elemental:
    description: Access elemental selection or help lore.
    usage: /elemental [set/help] [player] [element]
  controls:
    description: Toggle or view the Sneak+Swap hotkey system.
  spawnarchon:
    description: Spawns the legendary Elemental Archon Boss.
    permission: elementsmp.admin
  ability:
    description: Manually trigger an elemental ability.
    usage: /ability [1/2]
permissions:
  elementsmp.admin:
    description: Grants access to administrative elemental commands.
    default: op
