name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: '1.21'
commands:
  ability:
  controls:
  give-reroll:
  elementsmp:
    description: "Usage: /elementsmp set <player> <element>"
  trust:
    description: "Trust a player to prevent ability damage."
  untrust:
    description: "Remove a player from your trust list."
