name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: "1.21"
description: An advanced 11-element system with passives, abilities, and domains.
commands:
  elemental:
    description: Master command for elements.
    usage: /elemental <set/help>
  ability:
    description: Trigger active ability.
    usage: /ability <1/2>
  controls:
    description: Toggle swap-hand hotkeys.
    usage: /controls
permissions:
  elementsmp.admin:
    description: Manage player elements.
    default: op
