name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: '1.21'
commands:
  ability:
    description: Use your elemental power.
  controls:
    description: Toggle between F-key and Commands.
  elements:
    description: Admin command for elements.
    permission: elements.admin
