name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: "1.21"
commands:
  elemental:
    description: Main command for elements and help.
    usage: /elemental <set/help>
  ability:
    description: Manually trigger an elemental ability.
    usage: /ability <1/2>
  controls:
    description: Toggle the sneak+swap hotkeys.
    usage: /controls
  trust:
    description: Trust a player to immune them from your effects.
    usage: /trust <player>
