commands:
  elementsmp:
    description: Main admin command for ElementSMP.
    permission: op
  ability:
    description: Use your element ability.
  controls:
    description: Toggle F-key hotkeys.
  give-reroll:
    description: Get a reroll star.
