name: ElementSMP
version: 1.2
main: me.kaloni.ElementSMP
api-version: '1.20'
author: Kaloni
description: Custom Elemental SMP with dual-cooldown Action Bar HUD.

commands:
  ability:
    description: Use ability 1 or 2.
    usage: /ability [1|2]
  controls:
    description: Toggle F-key hotkeys.
  give-reroll:
    description: Get a standard Reroll Star.
    permission: op
  give-chaos:
    description: Get a Chaos Reroll Star.
    permission: op
  elementsmp:
    description: Admin element setter.
    permission: op
