commands:
  ability:
    description: Trigger your elemental power.
    usage: /ability <1/2>
  controls:
    description: Toggle between F-key and Command mode.
  elements:
    description: View your current element info.
