name: ElementSMP
version: 2.0
main: me.kaloni.ElementSMP
api-version: '1.21'
commands:
  controls: {description: Toggle offhand controls}
  trust: {description: Immune a player}
  untrust: {description: Remove immunity}
  elemental: {description: Help and Lore}
  elementsmp: {description: Admin commands}
  give-reroll: {description: Give Reroll}
  give-chaos: {description: Give Chaos Reroll}
