name: ElementSMP
version: 1.0.8-SOVEREIGNTY
main: me.kaloni.ElementSMP
api-version: "1.21"
description: An advanced 11-element system with a dynamic Boss Archon.
commands:
  elemental:
    description: View elemental lore or set a player's element.
    usage: /elemental [set/help] [player] [element]
  spawnarchon:
    description: Spawns the legendary Elemental Archon Boss.
    permission: elementsmp.admin
permissions:
  elementsmp.admin:
    description: Allows administrative control over elements and bosses.
    default: op
