name: ElementSMP
version: 1.0.8-SOVEREIGNTY
main: me.kaloni.ElementSMP
api-version: "1.21"
description: Advanced 11-Element framework with Dynamic Boss AI and Domain Logic.
commands:
  elemental:
    description: Access elemental help or set a player's element.
    usage: /elemental [set/help] [player] [element]
  controls:
    description: Information on how to use abilities.
  spawnarchon:
    description: Admin command to spawn the Elemental Archon Boss.
    permission: elementsmp.admin
  ability:
    description: Manually trigger ability 1 or 2.
permissions:
  elementsmp.admin:
    description: Grants permission to manage elements and bosses.
    default: op
