name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: 1.20
author: Kaloni
commands:
  ability:
    description: Use your elemental ability.
  controls:
    description: Toggle F-Key hotkeys for abilities.
  give-reroll:
    description: Give yourself an Elemental Reroll.
    permission: elementsmp.admin
  give-chaos:
    description: Give yourself a Chaos Reroll.
    permission: elementsmp.admin
  elementsmp:
    description: Admin commands for elements.
    permission: elementsmp.admin
