name: ElementSMP
version: 1.5
main: me.kaloni.ElementSMP
api-version: '1.21'
commands:
  ability:
    description: Use ability 1 or 2.
  elementsmp:
    description: Admin element control.
  trust:
    description: Trust a player.
  give-chaos:
    description: Give chaos star.
  give-reroll:
    description: Give reroll star.
