name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: '1.21'
commands:
  ability:
    description: Trigger your power.
  controls:
    description: Toggle swap-hand triggers.
  trust:
    description: Trust a teammate.
  untrust:
    description: Untrust a teammate.
  give-reroll:
    permission: elementsmp.admin
  give-chaos:
    permission: elementsmp.admin
  elementsmp:
    description: Main admin command.
    permission: elementsmp.admin
permissions:
  elementsmp.admin:
    default: op
