name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: '1.21'
commands:
  ability:
    description: Use your elemental power.
  controls:
    description: Toggle between hotkeys and commands.
  elementsmp:
    description: Admin command to set elements.
  trust:
    description: Trust a player for your domain.
  untrust:
    description: Remove trust from a player.
  give-reroll:
    description: Give an elemental reroll star.
  give-chaos:
    description: Give a chaos reroll star.
