name: ElementSMP
version: 1.0
main: me.kaloni.ElementSMP
api-version: 1.20 # Or your specific server version
commands:
  elemental:
    description: Set a player's element.
    usage: /elemental set <player> <element>
  ability:
    description: Trigger an ability.
    usage: /ability <1/2>
  controls:
    description: Toggle hotkeys.
    usage: /controls
