name: ElementSMP
version: 1.0.8-MASTER
main: me.kaloni.ElementSMP
api-version: "1.21"
description: An advanced 11-element framework with custom ability names and lore.
commands:
  elemental:
    description: Access elemental help or set a player's element.
    usage: /elemental [set/help] [player] [element]
  spawnarchon:
    description: Admin command to spawn the Elemental Archon Boss.
    permission: elementsmp.admin
permissions:
  elementsmp.admin:
    description: Allows spawning bosses and setting player elements.
    default: op
